version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - NETCDF_FILE=/data/e5.oper.an.sfc.128_167_2t.ll025sc.2015050100_2015053123.nc
      - CARTOPY_DATA_DIR=/tmp/cartopy
    volumes:
      - ./data:/data:ro

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    environment:
      - API_URL=http://localhost:8000
    depends_on:
      - backend