apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.fullname" . }}-backend
spec:
  selector:
    app: {{ include "my-app.name" . }}-backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
  type: {{ .Values.backend.service.type }}

