apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-app.fullname" . }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "my-app.name" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "my-app.name" . }}-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          env:
            - name: NETCDF_FILE
              value: {{ .Values.backend.env.NETCDF_FILE }}
            - name: CARTOPY_DATA_DIR
              value: {{ .Values.backend.env.CARTOPY_DATA_DIR }}
          volumeMounts:
            - name: data-volume
              mountPath: {{ .Values.backend.volume.dataPath }}
              readOnly: true
      volumes:
        - name: data-volume
          hostPath:
            path: {{ .Values.backend.volume.hostPath }}
